apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cicd-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      description: URL Git repository
    - name: revision
      description: Branch atau commit SHA
      default: main
    - name: image-tag
      description: Tag untuk Docker image
      default: latest
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        # Generate nama unik untuk setiap run
        generateName: cicd-pipeline-run-
        namespace: tekton-pipelines
        labels:
          app: go-project
          trigger: github-webhook
      spec:
        pipelineRef:
          name: cicd-pipeline
        taskRunTemplate:
          serviceAccountName: tekton-sa
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: revision
            value: $(tt.params.revision)
          - name: image-tag
            # Ambil 7 karakter pertama dari commit SHA sebagai tag
            value: $(tt.params.image-tag)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace-pvc
        timeouts:
          pipeline: 1h0m0s
