apiVersion: v1
kind: Service
metadata:
  name: go-frontend-service
  namespace: dev
  labels:
    app: go-frontend
spec:
  type: LoadBalancer
  selector:
    app: go-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80          # Akses browser: http://localhost
      targetPort: 80    # Port Nginx di dalam pod frontend
